force-app-eal/main/eal/objects/EAL_LoggerEvent__e/EAL_LoggerEvent__e.object-meta.xml
<CustomObject>
    <label>EAL_LoggerEvent</label>
    <pluralLabel>EAL_LoggerEvents</pluralLabel>
</CustomObject>

force-app-eal/main/eal/objects/EAL_LoggerEvent__e/fields/Logger__c.field-meta.xml
<CustomField>
    <fullName>Logger__c</fullName>
    <description
  >make sure that this length is greater than the sum of the size of EAL_Logger.cls and the length of Log Message Field on Custom Logger Object.</description>
    <label>Logger</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app-eal/main/eal/classes/EAL_LoggerEventTriggerService.cls
/**
 * @name EAL_LoggerEventTriggerService.cls
 * @description service for LoggerEventTrigger
 */
public without sharing class EAL_LoggerEventTriggerService {
  /**
   * @description fetch all debugLogs
   */
  public static void fetchDebugLogs() {
    List<EAL_LoggerEvent__e> events = (List<EAL_LoggerEvent__e>) Trigger.new;
    for (EAL_LoggerEvent__e event : events) {
      EAL_Logger logger = (EAL_Logger) JSON.deserialize(
        event.Logger__c,
        EAL_Logger.class
      );
      logger.fetch();
    }
  }
}